default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: digital-resume-dev

test:
  <<: *default
  database: digital-resume-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
